### PR TITLE
#329: Debug field generation for redefined fields

### PR DESCRIPTION
**Pull request by chanduhawk**
This PR is for the debug field generation for redefined fields.

https://github.com/AbsaOSS/cobrix/issues/329

### CODE REVIEW

**Comment by yruslan** [comment]
Hi, sorry for the delay. Will take a look now.

**Review by yruslan — APPROVED** [review]
Thanks for your contribution!

This indeed looks like a very helpful feature, especially for redefined fields that have different data types and sizes.

P.S. One unit test failed after the change, but we can fix this on our side.

**Comment by yruslan** [comment]
Will fix the failing unit test and add one more test for a thing I want working surely.

Going to release a new version tomorrow.

**Comment by chanduhawk** [comment]
Thanks a lot for accepting the enhancement.

**Pull request merged**
