### PR TITLE
ANTLR4 Parser

### PR DESCRIPTION
**Pull request by tr11**
This PR includes a new parser based on [ANTLR4](https://www.antlr.org/) to validate and build the AST. The grammar is loosely based on the one at https://github.com/uwol/proleap-cobol-parser (MIT License). 

All the tests pass using the new parser except for the one mentioned on https://github.com/AbsaOSS/cobrix/issues/39#issuecomment-489654459 regarding signs.

### CODE REVIEW

**Comment by yruslan** [comment]
Wow, this is HUGE! Having a proper parser is something we have dreamed of for quite some time. It is a pleasure to review it. Thanks!!!

We are going to release a minor feature release (0.5.0) tomorrow that will include all bugfixes and features developed over the past couple of months. So the new parser will go into 0.6.0.

**Comment by yruslan** [comment]
Looked through the PR again and I like it! It is great to have a proper parser.

The only thing that is preventing from merging it is that we have a project requirement to have licenses in each file of the project. Even for generated files. Please, attach a license to each new file so that `mvn verify -Plicense-check` passes and then we can merge.

**Comment by tr11** [comment]
Some of the files are generated by ANTLR -- do you want to add licenses to those files?

**Comment by yruslan** [comment]
Yes. Sorry, I know how ridiculous this seems.

**Comment by tr11** [comment]
I totally get it.  I'll change the bash scripts to add the license to the generated files (to be fair, they don't need to be in the repo, but it's easier so we don't suddenly add a hard dependency for the ANTLR command line generator)

**Comment by yruslan** [comment]
Thanks!

**Comment by yruslan** [comment]
@tr11, really hope you didn't give up. We are very eager to merge this.

**Comment by tr11** [comment]
Sorry, I've been a bit busy with other things. I'll rebase it this week and add the licenses.

**Comment by yruslan** [comment]
Great, looking forward to.

**Comment by yruslan** [comment]
Freezing changes to the parser starting from now so you won't have to deal with incremental changes to the parser.

**Comment by tr11** [comment]
Failing two tests -- the one it always did (with the trailing + sign) and the new tests for leading and trailing signs.  My code gives a size of 8 for `SV9(7) SIGN LEADING`, seven for the number itself and another for the (explicit) sign.  Is that incorrect?

**Comment by yruslan** [comment]
Cobrix assumes punched sign by default. So `SV9(7) SIGN LEADING` assumed to be a punched sign (size=7) and `SV9(7) SIGN LEADING SEPARATE` assumes a separate digit for a sign (size=8). Will double check tomorrow if it is expected default behavior.

**Comment by tr11** [comment]
I was assuming on the parser that `SIGN LEADING/TRAILING` implicitly set the `SEPARATE` clause too.  If that's not the case I need to handle that case that.

**Comment by yruslan** [comment]
Checked the [spec (page 235)](https://www.ibm.com/support/knowledgecenter/SS6SG3_4.2.0/com.ibm.entcobol.doc_4.2/PGandLR/igy3lr50.pdf). If `SEPARATE` keyword is absent the signal is assumed to be punched.

> If the SEPARATE CHARACTER phrase is not specified, then:
> - The operational sign is presumed to be associated with the LEADING or
TRAILING digit position, whichever is specified, of the elementary numeric data
item. (In this instance, specification of SIGN IS TRAILING is the equivalent of
the standard action of the compiler.)
> - The character S in the PICTURE character string is not counted in determining
the size of the item (in terms of standard data format characters).

> If the SEPARATE CHARACTER phrase is specified, then:
> - The operational sign is presumed to be the LEADING or TRAILING character
position, whichever is specified, of the elementary numeric data item. This
character position is not a digit position.
> - The character S in the PICTURE character string is counted in determining the
size of the data item (in terms of standard data format characters).
> - '+' is the character used for the positive operational sign.
> - '-' is the character used for the negative operational sign.

**Comment by yruslan** [comment]
This is almost perfect. Just a one tiny bit. It is related to separate sign characters as well.

Currently one test fails due to size mismatches of the following fields:
```
          10  EX-NUM-INT01        PIC +9(8).
          10  EX-NUM-INT02        PIC 9(8)+.
          10  EX-NUM-INT03        PIC -9(8).
          10  EX-NUM-INT04        PIC Z(8)-.
          10  EX-NUM-DEC01        PIC +9(6)V99.
          10  EX-NUM-DEC02        PIC Z(6)VZZ-.
          10  EX-NUM-DEC03        PIC 9(6).99-.
```
Screenshot 2019-07-18 at 08 48 41

The size of `PIC +9(8)` in your PR is 8 bytes, while it is 9 in the `master`. I'm not 100% sure, but I thought that sign symbols, if included in PIC, imply a separate character for a sign according to page 213 of the [spec](https://www.ibm.com/support/knowledgecenter/SS6SG3_4.2.0/com.ibm.entcobol.doc_4.2/PGandLR/igy3lr50.pdf):
> (+/-) Each character used in the editing sign symbol is
counted as one character position in the size of the
data item.

Please take a look and let me know your opinion on this.

This is the last thing to be sorted before merging.

**Comment by tr11** [comment]
I was never sure about that one, hence why I left it unchanged.  I assume the logic would be the same for `PIC 9(8)+`, right?

**Comment by yruslan** [comment]
Yes, I guess so. It will be similar to `PIC S9(8) SIGN TRAILING SEPARATE`.

**Comment by tr11** [comment]
Wait a little, I have still have one test failure (related to `floats` and `doubles` for COMP1 and COMP2).  I should have it fixed today or tomorrow.

**Comment by yruslan** [comment]
Sure, will wait. Thanks!

**Comment by yruslan** [comment]
Cool, see the last commit. Will take another look at the whole thing and then merge.

**Pull request merged**
