### PR TITLE
#420 Add experimental support for 'FB' format

### LINKED ISSUE #420: Add support for FB record format
## Background
Currently, Cobrix supports: F, V, VB and D formats. The only record format missing is FB

## Feature
Add support for FB record format

More on record formats: https://www.ibm.com/docs/en/zos/2.3.0?topic=files-selecting-record-formats-non-vsam-data-sets
More on FB format: https://www.ibm.com/docs/en/zos/2.3.0?topic=sets-fixed-length-record-formats
More on BDW: https://www.ibm.com/docs/en/zos/2.3.0?topic=records-block-descriptor-word-bdw

### LINKED ISSUE #422: Broken bar(¦) is getting converted into unbroken bar (|)
## Describe the bug
When I am reading Mainframe file (EBCDIC_037) in Databricks Notebook with cobrix library,for one of the character(i.e broken bar - ¦ ) is getting changed to unbroken bar (｜).

Actually, when I set debug ='hex' option while reading the file , debug dataframe column value giving correct hexa decimal value(6A) but value on the normal df column giving incorrect hexadecimal value (7C).

Due to this we are seeing data mismatch between source vs cobrix read data.

Anyone can help to fix this? and can you please clarify why this change happening in cobrix ?

Broken - \x6a
Unbroken Bar - \x7c

## Expected behaviour
I should get same value as I see on the source.

### PR DESCRIPTION
**Pull request by yruslan**
Resolves #420 
Resolves #422

Added experimental support for fixed block record formats (`FB`). When the record format is 'FB' you need to specify either block length or number of records per
block. As with 'F' if `record_length` is not specified, it will be determined from the copybook.
```
.option("record_format", "FB")
.option("record_length", "250")
.option("block_length", "500")
```
or
```
.option("record_format", "FB")
.option("record_length", "250")
.option("records_per_block", "2")
```

More on fixed-length record formats: https://www.ibm.com/docs/en/zos/2.3.0?topic=sets-fixed-length-record-formats

### CODE REVIEW

**Comment by sree018** [comment]
Hi @yruslan 

I have four types of files in ebcdic format
     1. variable block with variable length record (VB-> able to parse file ) 
     2. variable block with fixed length record ( not able to parse )
              Custom record extractor implementation for VBVR data files, should it not use rawRecordExtractor?#412
              I am using above logic to convert file to fixed block and reading as F.
     3. fixed block with variable length record (V-> able to parse file)
     4. fixed block with fixed length record (F-> able to parse file )
    
    File_Type   BDW.   RDW  
     VBVR         yes      yes 
     VBFR          yes      no
     FBVR          no       yes
     FBFR          no         no 

if you provide record_format as VBVR,VBFR,FBVR and FBFR which will help us.
Unfortunately, due to security issues, I cant provide dummy files for variable block with fixed length files.

**Comment by yruslan** [comment]
@sree018 , I see that you can't provide a dummy data. But could you please provide a spec for VBFR?

The way I see it:
VBVR: `BDW` `RDW` **`DATA`** `RDW` **`DATA`** `RDW` **`DATA`** `BDW` `RDW` **`DATA`** `RDW` **`DATA`** `RDW` **`DATA`** (aka VB)
VBFR: `?` (has BDW, but not RDW??? I couldn't find a spec for such kind of files in IBM'd docs)
FBVR: `RDW` **`DATA`** `RDW` **`DATA`** `RDW` **`DATA`** `RDW` **`DATA`** `RDW` **`DATA`** `RDW` **`DATA`** (aka V, no BDW)
FBFR: **`DATA`** **`DATA`** **`DATA`** **`DATA`** **`DATA`** **`DATA`** (aka F and FB)

**Comment by yruslan** [comment]
Does this make any sense?
VBFR: `BDW` **`DATA`** **`DATA`** **`DATA`** `BDW` **`DATA`** **`DATA`** **`DATA`**

**Comment by sree018** [comment]
@yruslan thanks for info.
My file follow this pattern.
VBFR: BDW DATA DATA DATA BDW DATA DATA DATA
DATA is fixed length.
But, In my copy book we flattened RDW.
after adjusting copy book, I am able parse VBFR-> BDW + RDW(2,2)

**Comment by yruslan** [comment]
I'm glad you found a solution. I'll add support for
VBFR: BDW DATA DATA DATA BDW DATA DATA DATA
as well, for completion.

**Comment by yruslan** [comment]
@sree018, just added support for BDW without RDW. Use
```
.option("record_format", "FB")
.option("record_length", "250")
```
(250 - record length)
or
```
.option("record_format", "FB")
```

**Comment by sree018** [comment]
Hi @yruslan 

Incase of multi segment hierarchical copybook,

by using custom record extractor, how do i parse file ?

**Comment by sree018** [comment]
Hi @yruslan 


I have multi segmented binary file and able to parse it, if single segment column present. How do I parse multi segmented file with two segment columns present ?

ex: copybook
            
           01 MASTER-DATA.
              05 KEY-TYPE  PIC X(01).
              05 KEY-IND     PIC X(01).
     * KEY=A AND IND=0
              05 KEY-A0-REC.
                     10 DATA-FIELDS  PIC X(998).
       *KEY =B AND IND=0
              05 KEY-B0-REC REDEFINES KEY-A0-REC.
                     10 DATA-FIELDS PIC X(998).
      *KEY= 'A'-'F' AND IND=1
               05 KEY-01-REC REDEFINES KEY-B0-REC.
                     10 DATA-FIELDS PIC X(998).
      * KEY = 'A-F' AND IND=2
              05 KEY-02-REC REDEFINES KEY-01-REC.
                     10 DATA-FIELDS PIC X(998).

**Comment by yruslan** [comment]
Hi @sree018,

Please, create a new issue for this question.

**Pull request merged**
