### PR TITLE
Add comma as a valid separator for numeric values

### PR DESCRIPTION
**Pull request by tr11**
This PR adds support for numeric values with comma as the decimal separator. 

Fixes issue #240.

### CODE REVIEW

**Comment by yruslan** [comment]
@hamc17 , it seems CI does not trigger for PRs created by external contributors.

**Comment by a4032** [comment]
HI, the comma is indeed the most used decimal separator in west-europe. So If possible to fix this urgently? This is a blocking issue for us. Can you tell me when this will be available? 
If not possible, we could not use cobrix maven library in our databricks solution. 
thanks

**Comment by yruslan** [comment]
Hi, @a4032 ,
It is released as `2.0.2` already. It may take a couple of more hours to appear on Maven Central though,

**Comment by a4032** [comment]
unsuccessfully: 

picture clause =  PIC +9999999,99 USAGE DISPLAY.

installed library (maven) : za.co.absa.cobrix:spark-cobol_2.11:2.0.2

data = +0000100,00

after reading the file: the result = 'null'

when I use PIC X(11) it shows the correct value but is not numeric: '+0000100,00' 

can you verify again please ? 
thanks

**Comment by a4032** [comment]
Ye,s but I can installed it. So it is found in the maven library :

[cid:image001.png@01D5DAD4.F3017AA0]


 
Ronny Meeusen
 
extern INFORMATICUS           HTOK | IT
ronny.meeusen@securex.be | www.securex.be
 

- Confidentiality Notice - 
 This communication and the information it contains is intended (a) for the person(s) or organization(s) named above and for no other person or organization, and (b) may be confidential, legally privileged ​and protected by law. Unauthorized use, copying or disclosure of any of it may be unlawful! If you ​receive this communication in error, please notify us immediately, destroy any copies and delete it ​from your computer system. Please consult our disclaimer on our site www.securex.eu. Thank you. !

**Comment by yruslan** [comment]
I will take a look.

**Comment by yruslan** [comment]
The fix for the comma support has missed a fix for the decoder.
Currently, the fix is available in `2.0.3-SNAPSHOT`. It will be in `2.0.3` after the fix is covered with a regression test.

**Comment by a4032** [comment]
Ok, keep me posted. And thanks for the effort


 
Ronny Meeusen
 
extern INFORMATICUS           HTOK | IT
ronny.meeusen@securex.be | www.securex.be
 

- Confidentiality Notice - 
 This communication and the information it contains is intended (a) for the person(s) or organization(s) named above and for no other person or organization, and (b) may be confidential, legally privileged ​and protected by law. Unauthorized use, copying or disclosure of any of it may be unlawful! If you ​receive this communication in error, please notify us immediately, destroy any copies and delete it ​from your computer system. Please consult our disclaimer on our site www.securex.eu. Thank you. !

**Comment by tr11** [comment]
> The fix for the comma support has missed a fix for the decoder.
> Currently, the fix is available in `2.0.3-SNAPSHOT`. It will be in `2.0.3` after the fix is covered with a regression test.

Oops, didn't even remember to check the decoder side.  My bad, sorry!

**Comment by yruslan** [comment]
No worries. I should have checked it more thoroughly, but I'm ooo currently.

Thanks for the fix to the parser. It would have taken me much longer to figure it out.

**Comment by yruslan** [comment]
@a4032 , this should be fixed in `2.0.3`.

**Pull request merged**
