### PR TITLE
#477 Fixed NotSerializableException when using non-default logger implementations

### PR DESCRIPTION
**Pull request by joaquin021**
https://github.com/AbsaOSS/cobrix/issues/477
 Make all loggers `@transient` for compatibility with non-default logger implementations

### CODE REVIEW

**Comment by joaquin021** [comment]
Sorry, I am working on fix the problems with the tests.

**Comment by yruslan** [comment]
Build has failed for this PR. Will check on our side. But, could you please, check if `mvn clean test` or `sbt +test` works for you locally?

**Comment by joaquin021** [comment]
> Build has failed for this PR. Will check on our side. But, could you please, check if `mvn clean test` or `sbt +test` works for you locally?

It doesn't work locally. Sorry for not testing correctly before doing the PR.
Logger in `VarLenNestedReader` class is null when it is annotated as `transient` in the test phase. I am working to fix it as soon as possible.

**Comment by yruslan** [comment]
Cool, thanks!!

**Comment by joaquin021** [comment]
The problem was that when the logger is declared as transient, it needs a lazy initialization on the classes that have been serialized in a spark task because never has been initialized in the "new context" as global variable.

I have based my solution in spark implementation and mongo connector simplifying them.
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/internal/Logging.scala#L42
https://github.com/mongodb/mongo-spark/blob/master/src/main/scala/com/mongodb/spark/LoggingTrait.scala#L30

I create a trait used by the classes that needs a logger and initialize it transient and lazy.

`sbt +test` works for me locally.

I don't know if you agree'll with the solution.
If you don't like it I can try to search other ways.

**Comment by yruslan** [comment]
This is fantastic! Thank you very much for your contribution!

**Pull request merged**
